/* ═══════════════════════════════════════════════════
   Writer's Ground – Opportunities Data v2
   Structured for card-based UI
═══════════════════════════════════════════════════ */

const WG_DATA = {

  submissions: [
    { name: "Meanjin", org: "Meanjin Quarterly", region: "Australia", type: "Literary Journal",
      genres: ["Fiction","Essays","Poetry","Memoir"], deadline: "Rolling / Quarterly", fee: "Free",
      payment: "Paid", eligibility: "Australian writers primarily", status: "open",
      desc: "One of Australia's oldest and most prestigious literary journals, publishing fiction, essays, poetry, and memoir since 1940.",
      url: "https://meanjin.com.au/submit/" },
    { name: "Overland", org: "Overland Literary Journal", region: "Australia", type: "Literary Journal",
      genres: ["Fiction","Essays","Poetry","Non-fiction"], deadline: "Rolling", fee: "Free",
      payment: "Paid ($550 print / $150 online)", eligibility: "Open to all writers", status: "open",
      desc: "Progressive Australian literary journal publishing fiction, essays, poetry, and cultural commentary since 1954.",
      url: "https://overland.org.au/submit/" },
    { name: "Island Magazine", org: "Island Magazine", region: "Australia / NZ", type: "Literary Journal",
      genres: ["Fiction","Non-fiction","Poetry"], deadline: "Varies by issue", fee: "Free",
      payment: "Paid", eligibility: "Australia, NZ, Pacific writers", status: "check",
      desc: "Tasmania-based literary journal publishing Australian, New Zealand, and Pacific writers across fiction, poetry, and essays.",
      url: "https://islandmag.com/submit" },
    { name: "Griffith Review", org: "Griffith University", region: "Australia", type: "Literary Journal",
      genres: ["Essays","Reportage","Creative Non-fiction","Fiction","Memoir"], deadline: "Per themed issue", fee: "Free",
      payment: "Paid", eligibility: "Open to all writers", status: "open",
      desc: "Thematic literary journal publishing long-form essays, reportage, and creative non-fiction. Each edition explores a specific theme.",
      url: "https://griffithreview.com/submissions/" },
    { name: "Kill Your Darlings", org: "Kill Your Darlings", region: "Australia", type: "Online Literary Magazine",
      genres: ["Essays","Fiction","Reviews","Commentary"], deadline: "Rolling", fee: "Free",
      payment: "Paid", eligibility: "Open to all writers", status: "open",
      desc: "Contemporary Australian literary magazine focused on essays, fiction, reviews, and cultural commentary for a new generation of readers.",
      url: "https://www.killyourdarlings.com.au/submissions/" },
    { name: "Southerly", org: "English Association Sydney", region: "Australia", type: "Literary Journal",
      genres: ["Fiction","Poetry","Creative Non-fiction","Academic Essays"], deadline: "Rolling", fee: "Free",
      payment: "Paid", eligibility: "Australian and New Zealand authors", status: "open",
      desc: "Australia's oldest literary journal, published since 1939. Accepts fiction, poetry, creative non-fiction, and academic essays from AU/NZ authors.",
      url: "https://southerlyjournal.com.au/submissions/" },
    { name: "Westerly", org: "University of Western Australia", region: "Australia", type: "Literary Journal",
      genres: ["Short Stories","Poetry","Memoir","Creative Non-fiction","Essays"], deadline: "Rolling", fee: "Free",
      payment: "Paid", eligibility: "Open to all writers", status: "open",
      desc: "Australia's longest-running literary journal from UWA, publishing short stories, poetry, memoir, and creative non-fiction.",
      url: "https://westerlymag.com.au/submissions/" },
    { name: "Voiceworks", org: "Express Media", region: "Australia", type: "Literary Journal",
      genres: ["Fiction","Poetry","Non-fiction","Art"], deadline: "Per issue", fee: "Free",
      payment: "Paid", eligibility: "Young Australians (under 25)", status: "check",
      desc: "Australia's premier literary journal for young writers under 25. Publishes fiction, poetry, non-fiction, and art.",
      url: "https://expressmedia.org.au/voiceworks/" },
    { name: "Landfall / Tauraka", org: "Otago University Press", region: "New Zealand", type: "Literary Journal",
      genres: ["Fiction","Poetry","Essays","Reviews"], deadline: "Biannual", fee: "Free",
      payment: "Paid", eligibility: "NZ and Pacific writers", status: "check",
      desc: "New Zealand's leading literary journal, publishing fiction, poetry, essays, and reviews from NZ and Pacific writers since 1947.",
      url: "https://oup.nz/landfall-tauraka/" },
    { name: "Takahē Magazine", org: "Takahē Collective Trust", region: "New Zealand", type: "Literary Magazine",
      genres: ["Short Stories","Poetry"], deadline: "Rolling", fee: "Free",
      payment: "Paid", eligibility: "NZ writers and international writers", status: "open",
      desc: "New Zealand literary magazine publishing short stories and poetry from NZ writers and international contributors.",
      url: "https://takahe.org.nz/submit/" },
    { name: "Cordite Poetry Review", org: "Cordite Publishing", region: "Australia", type: "Poetry Journal",
      genres: ["Poetry","Poetics Research"], deadline: "Rolling", fee: "Free",
      payment: "Paid", eligibility: "Open to all writers", status: "open",
      desc: "Australia's leading online poetry journal, publishing contemporary poetry and poetics research from Australian and international poets.",
      url: "https://cordite.org.au/submit/" },
    { name: "Liminal Magazine", org: "Liminal", region: "Australia", type: "Literary Magazine",
      genres: ["Fiction","Essays","Poetry","Reviews"], deadline: "Rolling", fee: "Free",
      payment: "Paid", eligibility: "Asian-Australian writers", status: "open",
      desc: "Australia's only literary magazine dedicated to Asian-Australian writers and stories exploring Asian-Australian experience.",
      url: "https://www.liminalmagazine.com.au/submissions" },
    { name: "Mascara Literary Review", org: "Mascara", region: "Australia", type: "Literary Journal",
      genres: ["Fiction","Poetry","Creative Non-fiction"], deadline: "Rolling", fee: "Free",
      payment: "Paid", eligibility: "First Nations, CaLD, disabled, neurodivergent writers", status: "open",
      desc: "Dedicated to publishing work by First Nations, culturally and linguistically diverse, disabled, and neurodivergent writers.",
      url: "https://mascarareview.com/submissions/" },
    { name: "Aurealis", org: "Chimaera Publications", region: "Australia", type: "Speculative Fiction Magazine",
      genres: ["Science Fiction","Fantasy","Horror"], deadline: "Rolling", fee: "Free",
      payment: "Paid", eligibility: "Open to all writers", status: "open",
      desc: "Australia's longest-running speculative fiction magazine, publishing science fiction, fantasy, and horror since 1990.",
      url: "https://aurealis.com.au/submissions/" },
    { name: "The Suburban Review", org: "The Suburban Review", region: "Australia", type: "Literary Journal",
      genres: ["Fiction","Poetry","Essays","Experimental"], deadline: "Per issue", fee: "Free",
      payment: "Paid", eligibility: "Open to all, especially underrepresented voices", status: "check",
      desc: "Australian literary journal championing underrepresented voices across fiction, poetry, essays, and experimental forms.",
      url: "https://thesuburbanreview.com/submissions/" },
    { name: "Starling", org: "Starling Magazine", region: "New Zealand", type: "Literary Journal",
      genres: ["Poetry","Prose"], deadline: "Rolling", fee: "Free",
      payment: "Paid", eligibility: "New Zealand writers under 25", status: "open",
      desc: "New Zealand's literary journal for young writers under 25, publishing poetry and prose.",
      url: "https://starlingmag.com/submit/" },
    { name: "Portside Review", org: "Portside Review", region: "International", type: "Literary Journal",
      genres: ["Poetry","Prose","Essays","Reviews"], deadline: "Rolling", fee: "Free",
      payment: "Unpaid", eligibility: "Open to all writers", status: "open",
      desc: "Online literary journal publishing poetry, prose, essays, and reviews from writers around the world.",
      url: "https://portsidereview.com/submissions/" },
    { name: "Tin House Magazine", org: "Tin House", region: "International", type: "Literary Magazine",
      genres: ["Fiction","Non-fiction","Poetry"], deadline: "Rolling (closed summer)", fee: "Free",
      payment: "Paid", eligibility: "Open internationally", status: "open",
      desc: "One of the world's most respected literary magazines, publishing fiction, non-fiction, and poetry from international writers.",
      url: "https://tinhouse.com/submissions/" },
    { name: "Granta", org: "Granta Publications", region: "International", type: "Literary Magazine",
      genres: ["Fiction","Non-fiction","Memoir","Poetry"], deadline: "Rolling", fee: "Free",
      payment: "Paid", eligibility: "Open internationally", status: "open",
      desc: "Prestigious British literary magazine publishing the best new writing from around the world since 1889.",
      url: "https://granta.com/submissions/" },
    { name: "The Sun Magazine", org: "The Sun", region: "International", type: "Literary Magazine",
      genres: ["Fiction","Essays","Poetry","Memoir"], deadline: "Rolling", fee: "Free",
      payment: "Paid ($300–$2,000)", eligibility: "Open internationally", status: "open",
      desc: "Independent US literary magazine paying $300–$2,000 for fiction, essays, poetry, and memoir. No advertising.",
      url: "https://www.thesunmagazine.org/submit" },
    { name: "Ploughshares", org: "Emerson College", region: "International", type: "Literary Journal",
      genres: ["Fiction","Poetry","Essays"], deadline: "Rolling (check periods)", fee: "$3 (Submittable fee)",
      payment: "Paid ($25/page)", eligibility: "Open internationally", status: "open",
      desc: "Prestigious US literary journal paying $25 per page for fiction, poetry, and essays. Guest-edited by leading writers.",
      url: "https://www.pshares.org/submit" },
    { name: "Aniko Magazine", org: "Aniko Press", region: "Australia", type: "Literary Magazine",
      genres: ["Flash Fiction","Short Stories","Creative Non-fiction","Poetry"], deadline: "Rolling", fee: "Free",
      payment: "Paid ($125)", eligibility: "Open to all writers", status: "open",
      desc: "Australian literary magazine paying $125 per piece for flash fiction, short stories, creative non-fiction, and poetry.",
      url: "https://www.anikopress.com.au/submissions" },
    { name: "Turbine | Kapohau", org: "Victoria University of Wellington", region: "New Zealand", type: "Literary Journal",
      genres: ["Poetry","Fiction","Essays"], deadline: "Annual", fee: "Free",
      payment: "Paid", eligibility: "New Zealand writers", status: "annual",
      desc: "Annual New Zealand literary journal from Victoria University of Wellington, publishing poetry, fiction, and essays.",
      url: "https://www.wgtn.ac.nz/modernletters/turbine" },
    { name: "Magabala Books", org: "Magabala Books", region: "Australia", type: "Publisher / Journal",
      genres: ["Fiction","Non-fiction","Poetry","Children's"], deadline: "Rolling", fee: "Free",
      payment: "Paid (publishing contract)", eligibility: "Aboriginal and Torres Strait Islander writers only", status: "open",
      desc: "Australia's leading Aboriginal and Torres Strait Islander publishing house, accepting manuscripts from First Nations writers.",
      url: "https://www.magabala.com/pages/submissions" },
    { name: "Narrative Magazine", org: "Narrative Magazine", region: "International", type: "Literary Magazine",
      genres: ["Fiction","Non-fiction","Poetry"], deadline: "Rolling", fee: "$20 (general submissions)",
      payment: "Paid", eligibility: "Open internationally", status: "open",
      desc: "Major US literary magazine publishing fiction, non-fiction, and poetry. Offers a free student submission option.",
      url: "https://www.narrativemagazine.com/submit" },
  ],

  competitions: [
    { name: "Furious Fiction", org: "Australian Writers' Centre", region: "International", type: "Flash Fiction",
      genres: ["Flash Fiction"], deadline: "Monthly (first Friday)", fee: "Free",
      prize: "AUD $500 monthly", eligibility: "Open internationally (18+)", status: "ongoing",
      desc: "Monthly flash fiction competition with a new prompt every first Friday. Write 500 words in 55 hours. Free to enter, $500 prize.",
      url: "https://www.writerscentre.com.au/furious-fiction/" },
    { name: "ABR Elizabeth Jolley Prize", org: "Australian Book Review", region: "Australia", type: "Short Fiction",
      genres: ["Short Fiction"], deadline: "May (annually)", fee: "Free",
      prize: "$6,000 (1st), $4,000 (2nd), $2,500 (3rd)", eligibility: "Australian citizens and permanent residents", status: "annual",
      desc: "One of Australia's most prestigious short story prizes. Open to Australian citizens and permanent residents. Free to enter.",
      url: "https://www.australianbookreview.com.au/abr-prizes/elizabeth-jolley-short-story-prize" },
    { name: "Peter Porter Poetry Prize", org: "Australian Book Review", region: "Australia", type: "Poetry",
      genres: ["Poetry"], deadline: "October (annually)", fee: "Free",
      prize: "$6,000 (winner), $1,000 (shortlist ×4)", eligibility: "Open to all writers", status: "annual",
      desc: "Major Australian poetry prize named after the late Peter Porter. Open to all writers. Free to enter.",
      url: "https://www.australianbookreview.com.au/abr-prizes/peter-porter-poetry-prize" },
    { name: "Furphy Literary Award", org: "Furphy Story", region: "Australia", type: "Short Fiction",
      genres: ["Short Fiction"], deadline: "Annual", fee: "Free",
      prize: "$15,000 (1st), $3,000 (2nd), $2,000 (3rd)", eligibility: "Australian writers", status: "annual",
      desc: "Major Australian short story award with $20,000 in prizes. Open to Australian writers. Free to enter.",
      url: "https://www.furphystory.com.au/furphy-literary-award/" },
    { name: "Nillumbik Prize for Contemporary Writing", org: "Writers Victoria", region: "Australia", type: "Fiction, Non-fiction, Poetry",
      genres: ["Fiction","Non-fiction","Poetry"], deadline: "Biennial", fee: "Free",
      prize: "$17,500 total prize pool", eligibility: "Australian writers", status: "annual",
      desc: "Biennial prize celebrating contemporary writing across fiction, non-fiction, and poetry. Open to Australian writers.",
      url: "https://writersvictoria.org.au/nillumbik-prize/" },
    { name: "KYD Creative Non-Fiction Prize", org: "Kill Your Darlings", region: "Australia", type: "Creative Non-fiction",
      genres: ["Creative Non-fiction","Essays"], deadline: "September (annually)", fee: "Free (KYD membership)",
      prize: "$2,500 (1st), $1,000 (runner-up ×2)", eligibility: "Current KYD members", status: "annual",
      desc: "Annual prize for creative non-fiction and essays from Kill Your Darlings. Open to current KYD members.",
      url: "https://www.killyourdarlings.com.au/cnf-prize/" },
    { name: "Scarlet Stiletto Awards", org: "Sisters in Crime Australia", region: "Australia", type: "Crime Fiction",
      genres: ["Crime Fiction","Mystery"], deadline: "Annual (Aug/Sep)", fee: "Free",
      prize: "$13,050+ total prize pool", eligibility: "Australian women writers", status: "annual",
      desc: "Australia's premier crime fiction competition for women writers, with $13,000+ in prizes across multiple categories.",
      url: "https://www.sistersincrime.org.au/scarlet-stiletto-awards" },
    { name: "NZWC Short Story Competition", org: "NZ Writers' College", region: "New Zealand", type: "Short Fiction",
      genres: ["Short Fiction"], deadline: "September 30 annually", fee: "Free until May 31, then $15",
      prize: "Cash prizes", eligibility: "Open internationally", status: "annual",
      desc: "Annual short story competition from the New Zealand Writers' College. Free entry until May 31, then $15.",
      url: "https://www.nzwriterscollege.co.nz/the-new-zealand-writers-college-annual-short-story-writing-competition/" },
    { name: "Allen & Unwin Aotearoa NZ Fiction Prize", org: "Allen & Unwin NZ", region: "New Zealand", type: "Novel",
      genres: ["Fiction","Novel"], deadline: "March 31 annually", fee: "Free",
      prize: "Publishing contract + prize", eligibility: "New Zealand citizens or permanent residents", status: "annual",
      desc: "Annual prize for an unpublished novel manuscript. Winner receives a publishing contract with Allen & Unwin NZ.",
      url: "https://www.allenandunwin.co.nz/being-a-writer/allenandunwin-nz-fiction-prize" },
    { name: "Lane Cove Literary Awards", org: "Lane Cove Council", region: "Australia", type: "Short Fiction, Poetry, Travel Writing",
      genres: ["Short Fiction","Poetry","Travel Writing"], deadline: "August annually", fee: "$15.50",
      prize: "$2,000 (short story), $1,500 (poetry), $1,500 (travel)", eligibility: "Writers 16+", status: "annual",
      desc: "Annual awards across short story, poetry, and travel writing categories. Open to writers 16 and over.",
      url: "https://www.lanecove.nsw.gov.au/community/arts-and-culture/literary-awards" },
    { name: "Penguin Literary Prize", org: "Penguin Random House Australia", region: "Australia", type: "Novel",
      genres: ["Fiction","Novel"], deadline: "Annual (opens November)", fee: "Free",
      prize: "$20,000 + publishing contract", eligibility: "Australian residents 18+", status: "annual",
      desc: "Annual prize for an unpublished novel manuscript. Winner receives $20,000 and a publishing contract with Penguin.",
      url: "https://www.penguinrandomhouse.com.au/penguin-literary-prize" },
    { name: "Bridport Prize", org: "Bridport Arts Centre", region: "International", type: "Short Fiction, Poetry, Flash Fiction",
      genres: ["Short Fiction","Poetry","Flash Fiction","Novel"], deadline: "May 31 annually", fee: "£9–£12 per entry",
      prize: "£5,000 (short story), £5,000 (poetry), £1,000 (flash)", eligibility: "Open internationally (16+)", status: "annual",
      desc: "One of the world's most prestigious writing competitions, with £11,000+ in prizes across short story, poetry, and flash fiction.",
      url: "https://bridportprize.org.uk/" },
    { name: "Bath Flash Fiction Award", org: "Bath Flash Fiction Award", region: "International", type: "Flash Fiction",
      genres: ["Flash Fiction"], deadline: "Rolling rounds", fee: "£8–£12 per entry",
      prize: "£1,000 (first prize)", eligibility: "Open internationally", status: "rolling",
      desc: "Prestigious international flash fiction competition with multiple rounds throughout the year. £1,000 first prize.",
      url: "https://www.bathflashfictionaward.com/" },
    { name: "Fish Publishing Prizes", org: "Fish Publishing", region: "International", type: "Short Fiction, Flash Fiction, Memoir, Poetry",
      genres: ["Short Fiction","Flash Fiction","Memoir","Poetry"], deadline: "November–March (varies)", fee: "€14–€20 per entry",
      prize: "€3,000 (short story), €1,000 (flash fiction)", eligibility: "Open internationally", status: "annual",
      desc: "Prestigious Irish writing competition across short story, flash fiction, memoir, and poetry categories.",
      url: "https://fishpublishing.com/writing-contests/" },
    { name: "Rattle Poetry Prize", org: "Rattle Magazine", region: "International", type: "Poetry",
      genres: ["Poetry"], deadline: "July 15 annually", fee: "$20 for up to 4 poems",
      prize: "$15,000 (winner), $500 (finalists ×10)", eligibility: "Open internationally (English language)", status: "annual",
      desc: "One of the world's richest poetry prizes, with $15,000 for the winner and $500 for each of 10 finalists.",
      url: "https://rattle.com/page/poetryprize/" },
    { name: "The Moth Short Story Prize", org: "The Moth Magazine", region: "International", type: "Short Fiction",
      genres: ["Short Fiction"], deadline: "Annual", fee: "€15 per entry",
      prize: "€6,000 (winner), €1,000 (runners-up ×3)", eligibility: "Open internationally", status: "annual",
      desc: "Prestigious Irish literary prize for short fiction. €6,000 for the winner, €1,000 each for three runners-up.",
      url: "https://themothmagazine.com/the-moth-short-story-prize/" },
    { name: "Not Quite Write Prize", org: "Not Quite Write", region: "International", type: "Flash Fiction",
      genres: ["Flash Fiction"], deadline: "Quarterly", fee: "Free",
      prize: "Cash prizes", eligibility: "Open internationally", status: "rolling",
      desc: "Quarterly flash fiction prize from Australian literary magazine Not Quite Write. Free to enter.",
      url: "https://notquitewrite.com/" },
    { name: "Woollahra Digital Literary Award", org: "Woollahra Council", region: "Australia", type: "Digital Writing",
      genres: ["Digital Fiction","Digital Non-fiction","Digital Poetry"], deadline: "August annually", fee: "Free",
      prize: "$7,500 total across categories", eligibility: "Australian writers", status: "annual",
      desc: "Annual award for digital writing across fiction, non-fiction, and poetry categories. Open to Australian writers.",
      url: "https://www.woollahra.nsw.gov.au/woollahra-digital-literary-award" },
    { name: "Heywire Competition", org: "ABC", region: "Australia", type: "Personal Essay",
      genres: ["Personal Essay","Audio","Video"], deadline: "September annually", fee: "Free",
      prize: "Trip to Canberra + mentoring", eligibility: "Young people 16–22 in regional/rural/remote Australia", status: "annual",
      desc: "ABC competition for young people 16–22 in regional, rural, and remote Australia to share their stories.",
      url: "https://www.abc.net.au/heywire/" },
    { name: "Marj Wilke Short Story Award", org: "Fellowship of Australian Writers (QLD)", region: "Australia", type: "Short Fiction",
      genres: ["Short Fiction"], deadline: "September 30 annually", fee: "$15 (or $40 for 3 entries)",
      prize: "$500 (1st), $350 (2nd), $125 (encouragement)", eligibility: "Australian women writers 18+", status: "annual",
      desc: "Annual short story award for Australian women writers 18 and over, run by the Fellowship of Australian Writers QLD.",
      url: "https://fawq.com.au/" },
  ],

  prizes: [
    { name: "Miles Franklin Literary Award", org: "Perpetual (Trustee)", region: "Australia",
      genres: ["Fiction","Novel"], value: "$60,000", deadline: "Annual (entries via publishers)", entry: "Publisher entry",
      eligibility: "Australian authors, published novel", status: "annual",
      desc: "Australia's most prestigious literary prize, awarded annually for a novel that presents Australian life. $60,000 prize.",
      url: "https://www.perpetual.com.au/miles-franklin" },
    { name: "Prime Minister's Literary Awards", org: "Creative Australia", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry","Children's","Young Adult","Australian History"], value: "$80,000 per category winner", deadline: "February annually (opens December)", entry: "Free (direct entry)",
      eligibility: "Australian citizens or permanent residents", status: "annual",
      desc: "Australia's richest literary prizes, with $80,000 for winners in each of six categories including fiction, non-fiction, and poetry.",
      url: "https://creative.gov.au/investments-opportunities/prime-ministers-literary-awards-2026" },
    { name: "Stella Prize", org: "The Stella Prize", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry"], value: "$60,000 (winner), $5,000 (shortlist)", deadline: "October annually", entry: "Free (direct entry)",
      eligibility: "Australian women and non-binary writers", status: "annual",
      desc: "Australia's most significant literary prize for women and non-binary writers. $60,000 for the winner, $5,000 for each shortlisted title.",
      url: "https://stella.org.au/" },
    { name: "NSW Premier's Literary Awards", org: "State Library of NSW / Create NSW", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry","Children's","YA","Playwriting","Indigenous Writing"], value: "$40,000 (fiction), $30,000–$40,000 (other categories)", deadline: "October annually", entry: "Publisher entry",
      eligibility: "Australian authors", status: "annual",
      desc: "Annual awards across multiple categories celebrating the best in Australian literature, administered by the State Library of NSW.",
      url: "https://www.sl.nsw.gov.au/awards/nsw-literary-awards" },
    { name: "Victorian Premier's Literary Awards", org: "The Wheeler Centre", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry","Drama","Children's","YA","Indigenous Writing"], value: "$100,000 (Victorian Prize), $25,000 (category winners)", deadline: "August annually", entry: "Publisher entry",
      eligibility: "Australian authors", status: "annual",
      desc: "Victoria's premier literary awards, including the $100,000 Victorian Prize for Literature. Administered by the Wheeler Centre.",
      url: "https://www.wheelercentre.com/victorian-premier-s-literary-awards" },
    { name: "Queensland Literary Awards", org: "Brisbane Writers Festival", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry","Children's","Young Adult"], value: "$30,000 (Premier's Award), $15,000 (Young Writers)", deadline: "April annually", entry: "Publisher entry",
      eligibility: "Australian authors", status: "annual",
      desc: "Annual Queensland literary awards including the Premier's Award and Young Writers Prize. Administered by Brisbane Writers Festival.",
      url: "https://bwf.org.au/queensland-literary-awards" },
    { name: "South Australian Literary Awards", org: "State Library of South Australia", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry","Children's","Young Adult"], value: "Varies by category", deadline: "Biennial (October)", entry: "Free (direct entry)",
      eligibility: "Australian authors (some categories SA-specific)", status: "annual",
      desc: "Biennial awards celebrating South Australian literature, with some categories open to all Australian authors.",
      url: "https://www.slsa.sa.gov.au/south-australian-literary-awards" },
    { name: "Ockham New Zealand Book Awards", org: "NZ Book Awards Trust", region: "New Zealand",
      genres: ["Fiction","Poetry","Non-fiction","Illustrated Non-fiction"], value: "$65,000 (fiction), $12,000 (other categories)", deadline: "Annual (entries via publishers)", entry: "Publisher entry",
      eligibility: "New Zealand authors", status: "annual",
      desc: "New Zealand's most prestigious book awards, with $65,000 for the fiction winner. Entries submitted by publishers.",
      url: "https://www.nzbookawards.nz/" },
    { name: "Australian/Vogel Literary Award", org: "Allen & Unwin / The Australian", region: "Australia",
      genres: ["Fiction","Non-fiction"], value: "$20,000 + publication", deadline: "May annually", entry: "Free (direct entry)",
      eligibility: "Australian writers under 35, unpublished manuscript", status: "annual",
      desc: "Australia's richest prize for an unpublished manuscript by a writer under 35. $20,000 prize plus publication by Allen & Unwin.",
      url: "https://www.allenandunwin.com/being-a-writer/vogel-literary-award" },
    { name: "Copyright Agency Author Fellowship", org: "Copyright Agency", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry","Playwriting","Children's"], value: "$80,000", deadline: "August annually (opens April)", entry: "Free (direct entry)",
      eligibility: "Australian citizens/PR, 5+ published full-length works", status: "annual",
      desc: "Australia's richest fellowship for established authors, providing $80,000 to develop a significant new work.",
      url: "https://www.copyright.com.au/culturalfund/fellowship/" },
    { name: "Paragraph Fellowship", org: "Time to Write", region: "Australia",
      genres: ["Literary Fiction"], value: "$25,000", deadline: "Annual", entry: "Free (direct entry)",
      eligibility: "Emerging/early career Australian writers of literary fiction", status: "annual",
      desc: "$25,000 fellowship for emerging and early career Australian writers of literary fiction.",
      url: "https://www.timetowrite.au/paragraph-fellowship" },
    { name: "Booker Prize", org: "Booker Prize Foundation", region: "International",
      genres: ["Fiction","Novel"], value: "£50,000", deadline: "Annual (entries via publishers)", entry: "Publisher entry",
      eligibility: "Authors writing in English, published in UK", status: "annual",
      desc: "The world's most prestigious prize for English-language fiction. £50,000 for the winner. Entries submitted by publishers.",
      url: "https://thebookerprizes.com/" },
    { name: "International Booker Prize", org: "Booker Prize Foundation", region: "International",
      genres: ["Fiction in Translation"], value: "£50,000 (split author/translator)", deadline: "Annual (entries via publishers)", entry: "Publisher entry",
      eligibility: "Any nationality, translated into English", status: "annual",
      desc: "Celebrates the best fiction translated into English. £50,000 split equally between author and translator.",
      url: "https://thebookerprizes.com/international-booker-prize" },
    { name: "Griffin Poetry Prize", org: "Griffin Trust for Excellence in Poetry", region: "International",
      genres: ["Poetry"], value: "$130,000 CAD (international), $10,000 CAD (Canadian)", deadline: "Annual (entries via publishers)", entry: "Publisher entry",
      eligibility: "International (any nationality), published in English", status: "annual",
      desc: "The world's largest prize for a single poetry collection. $130,000 CAD for the international winner.",
      url: "https://griffinpoetryprize.com/" },
    { name: "Costa Book Awards", org: "Costa Coffee", region: "International",
      genres: ["Fiction","Non-fiction","Poetry","Biography","Children's"], value: "£5,000 per category, £30,000 overall winner", deadline: "Annual (entries via publishers)", entry: "Publisher entry",
      eligibility: "UK/Ireland resident authors (6+ months in last 3 years)", status: "annual",
      desc: "Major UK literary awards across five categories, with a £30,000 prize for the overall Book of the Year.",
      url: "https://www.costabookawards.com/" },
    { name: "Hazel Rowley Literary Fellowship", org: "Writers Victoria", region: "Australia",
      genres: ["Biography","Life Writing"], value: "Cash prize + support", deadline: "Annual", entry: "Free (direct entry)",
      eligibility: "Australian writers working on biography/life writing", status: "annual",
      desc: "Annual fellowship supporting Australian writers working on biography, memoir, or life writing projects.",
      url: "https://writersvictoria.org.au/hazel-rowley-fellowship/" },
  ],

  fellowships: [
    { name: "Copyright Agency Author Fellowship", org: "Copyright Agency", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry","Playwriting","Children's"], value: "$80,000", duration: "1 year",
      deadline: "August annually (opens April)", fee: "Free",
      eligibility: "Australian citizens/PR, 5+ published full-length works, publisher interest", status: "annual",
      desc: "Australia's richest fellowship for established authors. $80,000 to develop a significant new work. Requires 5+ published books and publisher interest.",
      url: "https://www.copyright.com.au/culturalfund/fellowship/" },
    { name: "Copyright Agency Non-Fiction Fellowship", org: "Copyright Agency", region: "Australia",
      genres: ["Non-fiction","Memoir","Biography","History"], value: "$80,000", duration: "1 year",
      deadline: "August annually (opens April)", fee: "Free",
      eligibility: "Australian citizens/PR, 2+ published full-length books, publisher interest", status: "annual",
      desc: "$80,000 fellowship for established Australian non-fiction writers. Requires 2+ published books and publisher interest.",
      url: "https://www.copyright.com.au/culturalfund/fellowship/" },
    { name: "Copyright Agency Frank Moorhouse Fellowship", org: "Copyright Agency", region: "Australia",
      genres: ["Fiction"], value: "$10,000", duration: "1 year",
      deadline: "June annually (opens March)", fee: "Free",
      eligibility: "Australian citizens/PR, aged 18–35, no published full-length fiction", status: "annual",
      desc: "$10,000 fellowship for emerging Australian fiction writers aged 18–35 with no published full-length fiction.",
      url: "https://www.copyright.com.au/culturalfund/fellowship/" },
    { name: "The Next Chapter Program", org: "Writing NSW / Varuna", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry","All genres"], value: "$15,000 stipend + mentoring", duration: "Program year",
      deadline: "August annually", fee: "Free",
      eligibility: "Australian writers with underrepresented stories", status: "annual",
      desc: "$15,000 stipend plus mentoring for Australian writers with underrepresented stories. Run by Writing NSW and Varuna.",
      url: "https://writingnsw.org.au/the-next-chapter/" },
    { name: "Peter Blazey Fellowship", org: "Copyright Agency / Peter Blazey Fund", region: "Australia",
      genres: ["Non-fiction","Biography","Memoir","Life Writing"], value: "$20,000", duration: "Project-based",
      deadline: "August annually", fee: "Free",
      eligibility: "Writers with a publishing record in biography/memoir/life writing", status: "annual",
      desc: "$20,000 fellowship for writers with a publishing record working on biography, memoir, or life writing.",
      url: "https://www.copyright.com.au/culturalfund/fellowship/peter-blazey-fellowship/" },
    { name: "Marten Bequest Travelling Scholarships", org: "Creative Australia / Perpetual", region: "Australia",
      genres: ["Poetry","All arts"], value: "$50,000 (paid quarterly over 2 years)", duration: "2 years",
      deadline: "February annually", fee: "Free",
      eligibility: "Australian citizens aged 21–35", status: "annual",
      desc: "$50,000 over two years for Australian artists aged 21–35 to travel and develop their practice. Includes poetry.",
      url: "https://creative.gov.au/investments-opportunities/marten-bequest-travelling-scholarships" },
    { name: "Paragraph Fellowship", org: "Time to Write", region: "Australia",
      genres: ["Literary Fiction"], value: "$25,000", duration: "Project-based",
      deadline: "Annual", fee: "Free",
      eligibility: "Emerging/early career Australian writers of literary fiction", status: "annual",
      desc: "$25,000 fellowship for emerging and early career Australian writers of literary fiction to develop a significant work.",
      url: "https://www.timetowrite.au/paragraph-fellowship" },
    { name: "Varuna Red Room Poetry Fellowship", org: "Varuna / Red Room Poetry", region: "Australia",
      genres: ["Poetry"], value: "Residency + mentorship", duration: "1 week",
      deadline: "February annually", fee: "Free",
      eligibility: "Australian poets (emerging, no more than one collection)", status: "annual",
      desc: "Fully funded residential fellowship at Varuna for emerging Australian poets with no more than one published collection.",
      url: "https://www.varuna.com.au/" },
    { name: "Hazel Rowley Literary Fellowship", org: "Writers Victoria", region: "Australia",
      genres: ["Biography","Life Writing"], value: "Cash prize + support", duration: "Project-based",
      deadline: "Annual", fee: "Free",
      eligibility: "Australian writers working on biography/life writing", status: "annual",
      desc: "Annual fellowship supporting Australian writers working on biography, memoir, or life writing projects.",
      url: "https://writersvictoria.org.au/hazel-rowley-fellowship/" },
    { name: "National Library Creative Arts Fellowship", org: "National Library of Australia", region: "Australia",
      genres: ["All genres"], value: "Stipend + research support", duration: "Project-based",
      deadline: "Annual", fee: "Free",
      eligibility: "Australian writers", status: "annual",
      desc: "Fellowship supporting Australian writers to use the National Library's collections in developing a new creative work.",
      url: "https://www.library.gov.au/research/fellowships-and-scholarships/creative-arts-fellowship" },
    { name: "Hedberg Writer-in-Residence Program", org: "University of Tasmania", region: "Australia",
      genres: ["All genres"], value: "Stipend + accommodation", duration: "1 year",
      deadline: "November annually", fee: "Free",
      eligibility: "Australian writers", status: "annual",
      desc: "Year-long writer-in-residence fellowship at the University of Tasmania, including stipend and accommodation.",
      url: "https://www.utas.edu.au/community-and-partners/hedberg-writer-in-residence" },
    { name: "Judy Harris Writer-in-Residence Fellowship", org: "University of Sydney / Charles Perkins Centre", region: "Australia",
      genres: ["All genres"], value: "$100,000", duration: "1 year",
      deadline: "Annual", fee: "Free",
      eligibility: "Australian creative writers", status: "annual",
      desc: "$100,000 writer-in-residence fellowship at the University of Sydney's Charles Perkins Centre. One of Australia's richest.",
      url: "https://www.sydney.edu.au/charles-perkins-centre/our-research/initiatives/writer-in-residence.html" },
    { name: "Winston Churchill McNeish Writer's Fellowship", org: "NZ Society of Authors", region: "New Zealand",
      genres: ["All genres"], value: "Cash award", duration: "Project-based",
      deadline: "Biennial", fee: "Free",
      eligibility: "New Zealand writers", status: "annual",
      desc: "Biennial fellowship from the New Zealand Society of Authors supporting established NZ writers to develop new work.",
      url: "https://authors.org.nz/" },
    { name: "Copyright Agency Reading Australia Fellowship", org: "Copyright Agency", region: "Australia",
      genres: ["Education / Teaching"], value: "$15,000", duration: "1 year",
      deadline: "May annually (opens February)", fee: "Free",
      eligibility: "Australian teachers/teacher librarians", status: "annual",
      desc: "$15,000 fellowship for Australian teachers and teacher librarians to develop resources promoting Australian literature.",
      url: "https://www.copyright.com.au/culturalfund/fellowship/" },
  ],

  residencies: [
    { name: "Varuna Residential Fellowships", org: "Varuna, The National Writers' House", region: "Australia", location: "Katoomba, NSW",
      genres: ["All genres"], value: "Fully subsidised residency", duration: "1–4 weeks",
      deadline: "May annually (for following year)", fee: "Free",
      eligibility: "Australian writers (various fellowship pathways)", status: "annual",
      desc: "Australia's premier writers' residency in the Blue Mountains. Multiple fellowship pathways for emerging and established writers.",
      url: "https://www.varuna.com.au/" },
    { name: "Bundanon Artists in Residence", org: "Bundanon", region: "Australia", location: "Illaroo, NSW",
      genres: ["All arts disciplines"], value: "Accommodation + studio space", duration: "1–3 weeks",
      deadline: "Annual (opens early each year)", fee: "Free",
      eligibility: "Open internationally (all disciplines)", status: "annual",
      desc: "Residency at Arthur Boyd's former property on the Shoalhaven River. Open to artists of all disciplines internationally.",
      url: "https://www.bundanon.com.au/residencies/" },
    { name: "BR Whiting Studio Residency (Rome)", org: "Creative Australia", region: "Australia", location: "Rome, Italy",
      genres: ["Writing (all genres, especially poetry)"], value: "$5,000–$25,000 + studio accommodation", duration: "1, 3, or 6 months",
      deadline: "August annually (opens June)", fee: "Free",
      eligibility: "Australian citizens or permanent residents (practicing writers)", status: "annual",
      desc: "Prestigious residency at a studio apartment in Rome for Australian writers. $5,000–$25,000 stipend plus accommodation.",
      url: "https://creative.gov.au/investments-opportunities/br-whiting-studio-residency" },
    { name: "KSP Writers' Centre Residency", org: "Katharine Susannah Prichard Writers' Centre", region: "Australia", location: "Mundaring, WA",
      genres: ["All genres"], value: "Fully subsidised accommodation + studio", duration: "2–4 weeks",
      deadline: "Annual", fee: "Free",
      eligibility: "Australian writers (some categories WA-specific)", status: "annual",
      desc: "Fully subsidised residency at the KSP Writers' Centre in the Perth Hills. Some categories are WA-specific.",
      url: "https://www.kspwriterscentre.com/residency-program" },
    { name: "QWC Fishbowl Residency", org: "Queensland Writers Centre", region: "Australia", location: "Brisbane, QLD",
      genres: ["All genres"], value: "Workspace + 5 hours mentorship", duration: "10 weeks",
      deadline: "Rolling (year-round)", fee: "Free (QWC membership)",
      eligibility: "Australian citizens/PR, QWC members", status: "rolling",
      desc: "10-week workspace residency at Queensland Writers Centre with 5 hours of professional mentorship. Rolling applications.",
      url: "https://queenslandwriters.org.au/residencies" },
    { name: "QWC Flinthart Residency", org: "Queensland Writers Centre", region: "Australia", location: "Brisbane, QLD",
      genres: ["All genres"], value: "$1,000 stipend + workspace + mentorship", duration: "10 weeks",
      deadline: "July annually (opens June)", fee: "Free (QWC membership)",
      eligibility: "Australian citizens/PR, QWC members", status: "annual",
      desc: "$1,000 stipend plus workspace and mentorship at Queensland Writers Centre. For writers exploring self-publishing.",
      url: "https://queenslandwriters.org.au/residencies" },
    { name: "Abbotsford Convent Writers Residency", org: "Abbotsford Convent", region: "Australia", location: "Melbourne, VIC",
      genres: ["All genres"], value: "Paid positions + studio space", duration: "Annual",
      deadline: "Annual (applications open February)", fee: "Free",
      eligibility: "Australian writers", status: "annual",
      desc: "Paid writer-in-residence positions at the Abbotsford Convent in Melbourne, with studio space and community engagement.",
      url: "https://abbotsfordconvent.com.au/residencies/" },
    { name: "Vaucluse House Creative Residency", org: "Sydney Living Museums", region: "Australia", location: "Sydney, NSW",
      genres: ["All creative disciplines"], value: "Fully subsidised studio access for 12 months", duration: "12 months",
      deadline: "September annually", fee: "Free",
      eligibility: "NSW-based creative practitioners", status: "annual",
      desc: "12-month studio residency at the historic Vaucluse House for NSW-based creative practitioners including writers.",
      url: "https://sydneylivingmuseums.com.au/residency" },
    { name: "Michael King Writers Centre Residency", org: "Michael King Writers Centre", region: "New Zealand", location: "Devonport, Auckland, NZ",
      genres: ["Fiction","Non-fiction","Children's","YA","Drama","Poetry"], value: "Accommodation + studio + stipend", duration: "2–4 weeks",
      deadline: "July annually (opens June)", fee: "Free",
      eligibility: "New Zealand citizens or permanent residents", status: "annual",
      desc: "New Zealand's premier writers' residency in Devonport, Auckland. Accommodation, studio, and stipend for NZ writers.",
      url: "https://writerscentre.org.nz/" },
    { name: "Victoria University Writer in Residence", org: "Victoria University of Wellington", region: "New Zealand", location: "Wellington, NZ",
      genres: ["All genres"], value: "Stipend + office space", duration: "1 year",
      deadline: "Annual", fee: "Free",
      eligibility: "New Zealand writers", status: "annual",
      desc: "Year-long writer-in-residence at Victoria University of Wellington, with stipend and office space at the International Institute of Modern Letters.",
      url: "https://www.wgtn.ac.nz/modernletters/about/residence" },
    { name: "University of Waikato Writer in Residence", org: "University of Waikato", region: "New Zealand", location: "Hamilton, NZ",
      genres: ["All genres"], value: "Stipend + office space", duration: "1 year",
      deadline: "Annual", fee: "Free",
      eligibility: "New Zealand residents and citizens", status: "annual",
      desc: "Year-long writer-in-residence at the University of Waikato in Hamilton, with stipend and office space.",
      url: "https://www.waikato.ac.nz/int/about/faculties-schools/arts/writing-studies/writer-in-residence/" },
    { name: "Dunedin City of Literature Residency", org: "Dunedin City of Literature", region: "New Zealand", location: "Dunedin, NZ",
      genres: ["All genres"], value: "Accommodation + stipend", duration: "6 weeks",
      deadline: "Annual", fee: "Free",
      eligibility: "NZ writers or writers from UNESCO Cities of Literature", status: "annual",
      desc: "6-week residency in Dunedin for NZ writers and writers from other UNESCO Cities of Literature.",
      url: "https://www.cityofliterature.co.nz/a-literary-city/residencies" },
    { name: "Fulbright-Creative NZ Pacific Writer's Residency", org: "Fulbright New Zealand / Creative NZ", region: "New Zealand", location: "Hawaii, USA",
      genres: ["All genres"], value: "Full Fulbright award (stipend, flights, accommodation)", duration: "Several months",
      deadline: "Annual", fee: "Free",
      eligibility: "Established NZ writers of Pacific heritage", status: "annual",
      desc: "Full Fulbright award for established New Zealand writers of Pacific heritage to undertake a residency in Hawaii.",
      url: "https://fulbright.org.nz/" },
    { name: "Yaddo", org: "Yaddo", region: "International", location: "Saratoga Springs, NY, USA",
      genres: ["Fiction","Poetry","Non-fiction","All creative disciplines"], value: "Fully subsidised (accommodation + meals + studio)", duration: "2 weeks to 2 months",
      deadline: "Rolling (check application periods)", fee: "Free",
      eligibility: "Professional creative artists from all nations", status: "rolling",
      desc: "One of the world's most prestigious artist residencies. Fully subsidised accommodation, meals, and studio space in upstate New York.",
      url: "https://yaddo.org/apply/" },
    { name: "MacDowell", org: "MacDowell", region: "International", location: "Peterborough, NH, USA",
      genres: ["Fiction","Poetry","Non-fiction","All creative disciplines"], value: "Fully subsidised (accommodation + meals + studio)", duration: "2 weeks to 2 months",
      deadline: "Rolling (spring and autumn periods)", fee: "Free",
      eligibility: "Professional artists from all nations", status: "rolling",
      desc: "America's oldest artist residency. Fully subsidised accommodation, meals, and studio space in New Hampshire.",
      url: "https://www.macdowell.org/" },
    { name: "Civitella Ranieri", org: "Civitella Ranieri Foundation", region: "International", location: "Umbertide, Italy",
      genres: ["Writing","Visual Arts","Music Composition"], value: "Fully subsidised (accommodation + studio + meals)", duration: "6 weeks",
      deadline: "Annual", fee: "Free",
      eligibility: "International artists (all nations)", status: "annual",
      desc: "Prestigious 6-week residency at a 15th-century castle in Umbria, Italy. Fully subsidised for writers, visual artists, and composers.",
      url: "https://civitella.org/" },
  ],

  education: [
    { name: "Australian Writers' Centre – Online Courses", org: "Australian Writers' Centre", region: "Australia / International",
      genres: ["Creative Writing","Freelance Writing","Copywriting","Business Writing"], cost: "$395–$650 per course",
      format: "Online (self-paced and tutor-led)", level: "Beginner to Advanced", status: "ongoing",
      desc: "Australia's leading writing school with 100+ courses in creative writing, freelance writing, copywriting, and business writing.",
      url: "https://www.writerscentre.com.au/" },
    { name: "Faber Writing Academy", org: "Faber Writing Academy / Allen & Unwin", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry","Crime","Speculative Fiction","YA","Memoir"], cost: "Varies ($500–$3,000+ per course)",
      format: "In-person and online", level: "Intermediate to Advanced", status: "ongoing",
      desc: "Prestigious writing academy offering intensive courses in fiction, non-fiction, poetry, and genre writing. Taught by published authors.",
      url: "https://faberwritingacademy.com.au/" },
    { name: "Writing NSW – Courses and Workshops", org: "Writing NSW", region: "Australia",
      genres: ["All genres"], cost: "Varies (some free for members)",
      format: "In-person and online", level: "All levels", status: "ongoing",
      desc: "NSW's peak body for writers, offering courses, workshops, and mentorships across all genres and career stages.",
      url: "https://writingnsw.org.au/" },
    { name: "Queensland Writers Centre – Courses", org: "Queensland Writers Centre", region: "Australia",
      genres: ["All genres"], cost: "Varies",
      format: "In-person and online", level: "All levels", status: "ongoing",
      desc: "Queensland's peak writing body offering courses, workshops, and mentorships for writers at all stages.",
      url: "https://queenslandwriters.org.au/" },
    { name: "Writers Victoria – Courses and Workshops", org: "Writers Victoria", region: "Australia",
      genres: ["All genres"], cost: "Varies (discounted for members)",
      format: "In-person and online", level: "All levels", status: "ongoing",
      desc: "Victoria's peak writing body offering courses, workshops, and mentorships for writers at all stages.",
      url: "https://writersvictoria.org.au/" },
    { name: "Varuna Creative Writing Courses", org: "Varuna, The National Writers' House", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry"], cost: "Varies",
      format: "In-person and online", level: "Intermediate to Advanced", status: "ongoing",
      desc: "Intensive writing courses at Australia's national writers' house in the Blue Mountains, taught by leading Australian authors.",
      url: "https://www.varuna.com.au/courses" },
    { name: "Writers SA – Workshops and Programs", org: "Writers SA", region: "Australia",
      genres: ["All genres"], cost: "Varies (some free for members)",
      format: "In-person and online", level: "All levels", status: "ongoing",
      desc: "South Australia's peak writing body offering workshops, programs, and mentorships for SA writers.",
      url: "https://writerssa.org.au/" },
    { name: "NZ Writers' College – Online Courses", org: "NZ Writers' College", region: "New Zealand / International",
      genres: ["Creative Writing","Journalism","Copywriting","Children's Writing"], cost: "Varies per course",
      format: "Online (self-paced)", level: "Beginner to Advanced", status: "ongoing",
      desc: "New Zealand's leading online writing school, offering courses in creative writing, journalism, copywriting, and children's writing.",
      url: "https://www.nzwriterscollege.co.nz/" },
    { name: "IIML – Victoria University of Wellington", org: "Victoria University of Wellington", region: "New Zealand",
      genres: ["Fiction","Non-fiction","Poetry","Screenwriting","Literary Translation"], cost: "University fees apply",
      format: "In-person", level: "Undergraduate to Postgraduate", status: "ongoing",
      desc: "New Zealand's leading creative writing school, offering undergraduate and postgraduate programs in fiction, poetry, screenwriting, and more.",
      url: "https://www.wgtn.ac.nz/modernletters" },
    { name: "University of Melbourne – Master of Creative Writing", org: "University of Melbourne", region: "Australia",
      genres: ["Creative Writing","Publishing","Editing"], cost: "University fees apply",
      format: "In-person", level: "Postgraduate", status: "ongoing",
      desc: "Australia's leading postgraduate program in creative writing, publishing, and editing at the University of Melbourne.",
      url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-creative-writing-publishing-and-editing/" },
    { name: "Emerging Writers' Festival", org: "Emerging Writers' Festival", region: "Australia",
      genres: ["All genres"], cost: "Varies (some free events)",
      format: "In-person and online", level: "Emerging writers", status: "annual",
      desc: "Annual festival dedicated to emerging writers, featuring workshops, panels, and networking events across Melbourne and online.",
      url: "https://emergingwritersfestival.org.au/" },
    { name: "Clarion Science Fiction & Fantasy Workshop", org: "Clarion", region: "International",
      genres: ["Science Fiction","Fantasy","Speculative Fiction"], cost: "~$5,500 (scholarships available)",
      format: "In-person residential", level: "Advanced", status: "annual",
      desc: "The world's most prestigious speculative fiction workshop. Six weeks, 18 students, taught by leading SF/F authors. Scholarships available.",
      url: "https://clarion.ucsd.edu/" },
    { name: "Tin House Summer Workshop", org: "Tin House", region: "International",
      genres: ["Fiction","Non-fiction","Poetry"], cost: "~$1,500–$2,000",
      format: "In-person residential", level: "Advanced", status: "annual",
      desc: "Prestigious week-long summer workshop in Portland, Oregon. Workshops in fiction, non-fiction, and poetry with leading authors.",
      url: "https://tinhouse.com/workshop/" },
    { name: "Coursera – Creative Writing Specialisation", org: "Wesleyan University / Coursera", region: "International",
      genres: ["Fiction","Poetry","Creative Non-fiction"], cost: "Free to audit / ~$49/month for certificate",
      format: "Online (self-paced)", level: "Beginner to Intermediate", status: "ongoing",
      desc: "Free-to-audit online specialisation in creative writing from Wesleyan University, covering fiction, poetry, and creative non-fiction.",
      url: "https://www.coursera.org/specializations/creative-writing" },
    { name: "Kenyon Review Writers Workshop", org: "Kenyon College", region: "International",
      genres: ["Fiction","Poetry","Non-fiction"], cost: "~$2,000–$3,000",
      format: "In-person and online", level: "All levels", status: "annual",
      desc: "Prestigious summer writing workshop from one of America's leading literary magazines. In-person and online options.",
      url: "https://kenyonreview.org/workshops/" },
  ],

  pays_writers: [
    // ── AUSTRALIA ──────────────────────────────────────
    { name: "Overland", org: "Overland Literary Journal", region: "Australia",
      genres: ["Fiction","Essays","Poetry","Non-fiction"], type: "Literary Journal",
      payRate: "$550 (print story/essay) · $150 (online) · $150 (poem)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Progressive Australian literary journal paying $550 for print fiction/essays, $150 for online pieces, and $150 per poem. One of Australia's most consistent paying markets.",
      url: "https://overland.org.au/submit/" },
    { name: "Griffith Review", org: "Griffith University", region: "Australia",
      genres: ["Essays","Creative Non-fiction","Reportage","Fiction","Memoir"], type: "Literary Journal",
      payRate: "$500 (online) · $0.75/word (print commission)",
      deadline: "Per themed issue", fee: "Free", status: "open",
      desc: "Thematic quarterly journal paying $500 flat for online pieces and $0.75/word for commissioned print work. Publishes essays, reportage, and creative non-fiction.",
      url: "https://griffithreview.com/submissions/" },
    { name: "Kill Your Darlings", org: "Kill Your Darlings", region: "Australia",
      genres: ["Essays","Fiction","Reviews","Commentary"], type: "Online Literary Magazine",
      payRate: "$700+ (non-fiction) · varies by piece",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Contemporary Australian literary magazine paying a minimum of $700 for non-fiction essays and cultural commentary. One of the better-paying AU online markets.",
      url: "https://www.killyourdarlings.com.au/submissions/" },
    { name: "Meanjin", org: "Meanjin Quarterly", region: "Australia",
      genres: ["Fiction","Essays","Poetry","Memoir"], type: "Literary Journal",
      payRate: "Paid (rates on acceptance)",
      deadline: "Rolling / Quarterly", fee: "Free", status: "open",
      desc: "One of Australia's oldest and most prestigious literary journals. Pays contributors upon acceptance. Rates confirmed at time of acceptance.",
      url: "https://meanjin.com.au/submit/" },
    { name: "Westerly", org: "University of Western Australia", region: "Australia",
      genres: ["Short Stories","Poetry","Memoir","Creative Non-fiction","Essays"], type: "Literary Journal",
      payRate: "AU$300 (prose) · AU$250 (1 poem) · AU$300 (poetic sequence) · AU$180 (online)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Australia's longest-running literary journal from UWA. Pays AU$300 for prose, AU$250 for a single poem, and AU$300 for a poetic sequence.",
      url: "https://westerlymag.com.au/submissions/" },
    { name: "Island Magazine", org: "Island Magazine", region: "Australia",
      genres: ["Fiction","Non-fiction","Poetry","Essays"], type: "Literary Journal",
      payRate: "Paid (rates on acceptance)",
      deadline: "Varies by issue", fee: "Free", status: "open",
      desc: "Tasmania-based literary journal paying contributors across fiction, poetry, and essays. Rates confirmed at time of acceptance.",
      url: "https://islandmag.com/submit" },
    { name: "Southerly", org: "English Association Sydney", region: "Australia",
      genres: ["Fiction","Poetry","Creative Non-fiction","Academic Essays"], type: "Literary Journal",
      payRate: "Paid (rates on acceptance)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Australia's oldest literary journal (est. 1939). Pays contributors for fiction, poetry, and creative non-fiction. Open to AU/NZ authors.",
      url: "https://southerlyjournal.com.au/submissions/" },
    { name: "Cordite Poetry Review", org: "Cordite Publishing", region: "Australia",
      genres: ["Poetry","Poetics Research"], type: "Poetry Journal",
      payRate: "Paid (rates on acceptance)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Australia's leading online poetry journal. Pays contributors for contemporary poetry and poetics research from Australian and international poets.",
      url: "https://cordite.org.au/submit/" },
    { name: "Liminal Magazine", org: "Liminal", region: "Australia",
      genres: ["Fiction","Essays","Poetry","Reviews"], type: "Literary Magazine",
      payRate: "Paid (rates on acceptance)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Australia's only literary magazine for Asian-Australian writers. Pays contributors for fiction, essays, poetry, and reviews.",
      url: "https://www.liminalmagazine.com.au/submissions" },
    { name: "Quadrant", org: "Quadrant Magazine", region: "Australia",
      genres: ["Short Stories","Essays","Poetry","Reviews"], type: "Literary Magazine",
      payRate: "Paid (rates on acceptance)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Long-running Australian journal of ideas, essays, literature, and poetry. Pays for short stories, essays, articles, and poetry.",
      url: "https://quadrant.org.au/about/submissions/" },
    { name: "Archer Magazine", org: "Archer Magazine", region: "Australia",
      genres: ["Essays","Non-fiction","Personal Essay"], type: "Online Magazine",
      payRate: "AU$100 (online piece, 800–1,200 words)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Australian publication about sexuality, gender, and identity. Pays AU$100 for online pieces of 800–1,200 words from writers of all experience levels.",
      url: "https://archermagazine.com.au/write-for-us/" },
    { name: "Voiceworks", org: "Express Media", region: "Australia",
      genres: ["Fiction","Poetry","Non-fiction","Art"], type: "Literary Journal",
      payRate: "Paid (rates on acceptance)",
      deadline: "Per issue", fee: "Free", status: "check",
      desc: "Australia's premier literary journal for young writers under 25. Pays contributors for fiction, poetry, non-fiction, and art.",
      url: "https://expressmedia.org.au/voiceworks/" },
    { name: "Aurealis", org: "Chimaera Publications", region: "Australia",
      genres: ["Science Fiction","Fantasy","Horror"], type: "Speculative Fiction Magazine",
      payRate: "Paid (rates on acceptance)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Australia's longest-running speculative fiction magazine (est. 1990). Pays for science fiction, fantasy, and horror short stories.",
      url: "https://aurealis.com.au/submissions/" },
    { name: "Aniko Magazine", org: "Aniko Press", region: "Australia",
      genres: ["Flash Fiction","Short Stories","Creative Non-fiction","Poetry"], type: "Literary Magazine",
      payRate: "AU$125 per accepted piece",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Australian literary magazine paying AU$125 per accepted piece across flash fiction, short stories, creative non-fiction, and poetry.",
      url: "https://www.anikopress.com.au/submissions" },
    // ── NEW ZEALAND ────────────────────────────────────
    { name: "Landfall / Tauraka", org: "Otago University Press", region: "New Zealand",
      genres: ["Fiction","Poetry","Essays","Reviews"], type: "Literary Journal",
      payRate: "Paid (rates on acceptance)",
      deadline: "Biannual", fee: "Free", status: "check",
      desc: "New Zealand's leading literary journal (est. 1947). Pays contributors for fiction, poetry, essays, and reviews from NZ and Pacific writers.",
      url: "https://oup.nz/landfall-tauraka/" },
    { name: "Takahē Magazine", org: "Takahē Collective Trust", region: "New Zealand",
      genres: ["Short Stories","Poetry"], type: "Literary Magazine",
      payRate: "Paid (rates on acceptance)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "New Zealand literary magazine paying contributors for short stories and poetry. Open to NZ writers and international contributors.",
      url: "https://takahe.org.nz/submit/" },
    { name: "Let's Travel Magazine", org: "Let's Travel", region: "New Zealand",
      genres: ["Travel Writing","Personal Essay","Non-fiction"], type: "Travel Magazine",
      payRate: "NZ$300 (unpublished) · NZ$500 (published writers)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Bi-monthly travel magazine covering NZ, Australia, and the South Pacific. Pays NZ$300 per story for new writers, NZ$500 for published writers.",
      url: "https://www.letstravel.co.nz/" },
    // ── INTERNATIONAL (MAJOR) ──────────────────────────
    { name: "The Sun Magazine", org: "The Sun", region: "International",
      genres: ["Fiction","Essays","Poetry","Memoir"], type: "Literary Magazine",
      payRate: "$300–$2,000 (fiction/essays) · $100–$250 (poetry)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Independent US literary magazine paying $300–$2,000 for fiction and essays, and $100–$250 for poetry. No advertising. One of the best-paying literary markets.",
      url: "https://www.thesunmagazine.org/submit" },
    { name: "Tin House Magazine", org: "Tin House", region: "International",
      genres: ["Fiction","Non-fiction","Poetry"], type: "Literary Magazine",
      payRate: "Paid (rates on acceptance)",
      deadline: "Rolling (closed summer)", fee: "Free", status: "open",
      desc: "One of the world's most respected literary magazines. Pays for fiction, non-fiction, and poetry. Closed to submissions in summer.",
      url: "https://tinhouse.com/submissions/" },
    { name: "Ploughshares", org: "Emerson College", region: "International",
      genres: ["Fiction","Poetry","Essays"], type: "Literary Journal",
      payRate: "$25/page (prose) · $25/poem (min $50)",
      deadline: "Rolling (check periods)", fee: "$3 (Submittable fee)", status: "open",
      desc: "Prestigious US literary journal paying $25 per page for prose and $25 per poem. Guest-edited by leading writers each issue.",
      url: "https://www.pshares.org/submit" },
    { name: "One Story", org: "One Story", region: "International",
      genres: ["Literary Fiction","Short Stories"], type: "Literary Magazine",
      payRate: "$500 per story + 25 contributor copies",
      deadline: "Rolling (check periods)", fee: "$3 (Submittable fee)", status: "open",
      desc: "Publishes one story per issue, 12 times a year. Pays $500 per story plus 25 contributor copies. Highly selective.",
      url: "https://www.one-story.com/submissions/" },
    { name: "Poetry Magazine", org: "Poetry Foundation", region: "International",
      genres: ["Poetry"], type: "Poetry Journal",
      payRate: "$300+ per poem (minimum)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Founded in Chicago in 1912. Pays a minimum of $300 per poem — one of the highest-paying poetry markets in the world.",
      url: "https://www.poetryfoundation.org/poetrymagazine/submit" },
    { name: "Clarkesworld Magazine", org: "Wyrm Publishing", region: "International",
      genres: ["Science Fiction","Fantasy"], type: "Speculative Fiction Magazine",
      payRate: "$0.12/word (original) · $0.03/word (reprint)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Hugo and World Fantasy Award-winning SF/F magazine. Pays $0.12/word for original fiction — professional SFWA rates.",
      url: "https://clarkesworldmagazine.com/submissions/" },
    { name: "Strange Horizons", org: "Strange Horizons", region: "International",
      genres: ["Science Fiction","Fantasy","Speculative Fiction"], type: "Speculative Fiction Magazine",
      payRate: "$0.10/word (fiction) · $50 (poem)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Prestigious speculative fiction magazine paying professional SFWA rates. $0.10/word for fiction, $50 per poem. Very low acceptance rate.",
      url: "https://strangehorizons.com/submit/" },
    { name: "Asimov's Science Fiction", org: "Dell Magazines", region: "International",
      genres: ["Science Fiction","Fantasy"], type: "Science Fiction Magazine",
      payRate: "$0.08–$0.10/word (stories) · $1/line (poetry)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "One of the world's most respected science fiction magazines. Pays $0.08–$0.10/word for stories and $1/line for poetry.",
      url: "https://www.asimovs.com/submissions/" },
    { name: "The Deadlands", org: "The Deadlands", region: "International",
      genres: ["Speculative Fiction","Horror","Poetry","Essays"], type: "Speculative Fiction Magazine",
      payRate: "$0.10/word (fiction) · $100 (essay) · $50 (poem)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Paying speculative fiction market focused on death, grief, and the afterlife. $0.10/word for fiction, $100 for essays, $50 for poems.",
      url: "https://thedeadlands.com/submit/" },
    { name: "Frontier Poetry", org: "Frontier Poetry", region: "International",
      genres: ["Poetry"], type: "Poetry Journal",
      payRate: "$50 per poem (up to $150 per submission)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Pays $50 per published poem, up to $150 per submission. Open to emerging poets who have not published more than one full-length collection.",
      url: "https://www.frontierpoetry.com/submit/" },
    { name: "Narrative Magazine", org: "Narrative Magazine", region: "International",
      genres: ["Fiction","Non-fiction","Poetry"], type: "Literary Magazine",
      payRate: "Paid (rates on acceptance)",
      deadline: "Rolling", fee: "$20 (general) / Free (student)", status: "open",
      desc: "Major US literary magazine paying for fiction, non-fiction, and poetry. Free submission option for students. Rates confirmed on acceptance.",
      url: "https://www.narrativemagazine.com/submit" },
    { name: "The Forge Literary Magazine", org: "The Forge", region: "International",
      genres: ["Fiction","Non-fiction"], type: "Literary Magazine",
      payRate: "$100 per piece",
      deadline: "Rolling (monthly cap)", fee: "Free (monthly cap)", status: "open",
      desc: "Pays $100 for accepted fiction and non-fiction. Submit early in the month — free submissions reset monthly when the cap is reached.",
      url: "https://forgelitmag.com/submit/" },
    { name: "Granta", org: "Granta Publications", region: "International",
      genres: ["Fiction","Non-fiction","Memoir","Reportage"], type: "Literary Magazine",
      payRate: "Paid (rates on acceptance)",
      deadline: "Rolling", fee: "Free", status: "open",
      desc: "Prestigious British literary magazine (est. 1889) paying for the best new writing from around the world. Rates confirmed on acceptance.",
      url: "https://granta.com/submissions/" },
  ],

  publishers: [
    { name: "Allen & Unwin", org: "Allen & Unwin", region: "Australia / NZ", location: "Sydney, NSW",
      genres: ["Adult Fiction","Non-fiction","Illustrated","Children's","Young Adult"], type: "Major Independent Publisher",
      submission: "Unsolicited (The Friday Pitch)", agent: false, status: "open",
      desc: "Australia's largest independent publisher. Accepts unsolicited manuscripts via The Friday Pitch — submit the first 10 pages every Friday.",
      url: "https://www.allenandunwin.com/being-a-writer/getting-published/submitting-your-work" },
    { name: "Text Publishing", org: "Text Publishing", region: "Australia / NZ", location: "Melbourne, VIC",
      genres: ["Literary Fiction","Commercial Fiction","Non-fiction","Crime","Thriller","Fantasy","Romance","YA"], type: "Independent Publisher",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "One of Australia's most respected independent publishers, known for literary fiction and quality non-fiction. Accepts unsolicited manuscripts.",
      url: "https://www.textpublishing.com.au/submissions" },
    { name: "Hachette Australia", org: "Hachette Livre", region: "Australia", location: "Sydney, NSW",
      genres: ["Fiction","Non-fiction","Children's","Young Adult"], type: "Major Publisher",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "Major international publisher accepting unsolicited manuscripts from Australian writers across fiction, non-fiction, and children's books.",
      url: "https://www.hachette.com.au/submissions" },
    { name: "Pan Macmillan Australia", org: "Pan Macmillan", region: "Australia", location: "Sydney, NSW",
      genres: ["Fiction","Non-fiction","Children's","Young Adult"], type: "Major Publisher",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "Major international publisher accepting unsolicited manuscripts from Australian writers. Part of the global Macmillan Publishers group.",
      url: "https://www.panmacmillan.com.au/submissions/" },
    { name: "Affirm Press", org: "Affirm Press", region: "Australia", location: "Melbourne, VIC",
      genres: ["Literary Fiction","Genre Fiction","Non-fiction","Children's"], type: "Independent Publisher",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "Melbourne-based independent publisher known for quality fiction and non-fiction. Accepts unsolicited manuscripts from Australian writers.",
      url: "https://www.affirmpress.com.au/submissions/" },
    { name: "Black Inc.", org: "Black Inc.", region: "Australia", location: "Melbourne, VIC",
      genres: ["Non-fiction","Literary Fiction","Poetry"], type: "Independent Publisher",
      submission: "Unsolicited accepted (Australian writers only)", agent: false, status: "open",
      desc: "Publisher of serious non-fiction, literary fiction, and poetry. Accepts unsolicited manuscripts from Australian writers only.",
      url: "https://www.blackincbooks.com.au/submissions" },
    { name: "Giramondo Publishing", org: "Giramondo Publishing", region: "Australia", location: "Western Sydney, NSW",
      genres: ["Poetry","Literary Fiction","Literary Non-fiction"], type: "Independent Publisher",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "Australia's leading publisher of poetry and literary fiction. Based at Western Sydney University. Accepts unsolicited manuscripts.",
      url: "https://giramondopublishing.com/submissions/" },
    { name: "Ultimo Press", org: "Ultimo Press", region: "Australia", location: "Sydney, NSW",
      genres: ["Literary Fiction","General Fiction","Non-fiction"], type: "Independent Publisher",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "Newer independent publisher making waves in Australian literary fiction and non-fiction. Accepts unsolicited manuscripts.",
      url: "https://www.ultimopress.com.au/submissions/" },
    { name: "Fremantle Press", org: "Fremantle Press", region: "Australia", location: "Fremantle, WA",
      genres: ["Literary Fiction","Genre Fiction","Non-fiction","Poetry","Children's","Young Adult"], type: "Independent Publisher",
      submission: "Unsolicited accepted (WA authors)", agent: false, status: "open",
      desc: "Western Australia's leading independent publisher. Primarily accepts manuscripts from WA authors across all genres.",
      url: "https://fremantlepress.com.au/submissions/" },
    { name: "UQP (University of Queensland Press)", org: "University of Queensland Press", region: "Australia", location: "Brisbane, QLD",
      genres: ["Fiction","Non-fiction","Poetry","Children's","Young Adult"], type: "University Press",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "One of Australia's oldest and most respected publishers, known for First Nations literature and Australian writing. Accepts unsolicited manuscripts.",
      url: "https://www.uqp.com.au/submissions/" },
    { name: "Scribe Publications", org: "Scribe", region: "Australia / International", location: "Melbourne, VIC / London, UK",
      genres: ["Fiction","Non-fiction"], type: "Independent Publisher",
      submission: "Unsolicited (specific windows)", agent: false, status: "check",
      desc: "Award-winning independent publisher with offices in Melbourne and London. Accepts unsolicited manuscripts during specific submission windows.",
      url: "https://scribepublications.com.au/submissions/" },
    { name: "Wakefield Press", org: "Wakefield Press", region: "Australia", location: "Adelaide, SA",
      genres: ["Literary Fiction","Genre Fiction","Non-fiction","Young Adult"], type: "Independent Publisher",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "South Australia's leading independent publisher. Accepts unsolicited manuscripts from Australian writers across fiction and non-fiction.",
      url: "https://www.wakefieldpress.com.au/submissions/" },
    { name: "Magabala Books", org: "Magabala Books", region: "Australia", location: "Broome, WA",
      genres: ["Fiction","Non-fiction","Poetry","Children's","Memoir"], type: "Independent Publisher (Indigenous)",
      submission: "Unsolicited accepted (Indigenous authors only)", agent: false, status: "open",
      desc: "Australia's leading Aboriginal and Torres Strait Islander publishing house. Accepts manuscripts from First Nations writers only.",
      url: "https://www.magabala.com/pages/submissions" },
    { name: "Pantera Press", org: "Pantera Press", region: "Australia", location: "Sydney, NSW",
      genres: ["Fiction","Non-fiction"], type: "Independent Publisher",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "Independent Australian publisher known for commercial fiction and narrative non-fiction. Accepts unsolicited manuscripts.",
      url: "https://www.panterapress.com.au/submissions/" },
    { name: "Hardie Grant", org: "Hardie Grant", region: "Australia / International", location: "Melbourne, VIC",
      genres: ["Non-fiction","Illustrated","Children's","Young Adult"], type: "Independent Publisher",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "Melbourne-based independent publisher specialising in non-fiction, illustrated books, and children's titles. Accepts unsolicited manuscripts.",
      url: "https://www.hardiegrant.com/au/publishing/submissions/" },
    { name: "Te Herenga Waka University Press", org: "Victoria University of Wellington", region: "New Zealand", location: "Wellington, NZ",
      genres: ["Literary Fiction","Memoir","Essays","Poetry"], type: "University Press",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "New Zealand's leading literary publisher, publishing fiction, memoir, essays, and poetry. Accepts unsolicited manuscripts.",
      url: "https://teherengawakapress.co.nz/pages/submissions" },
    { name: "Otago University Press", org: "University of Otago", region: "New Zealand", location: "Dunedin, NZ",
      genres: ["Non-fiction","Poetry","Fiction"], type: "University Press",
      submission: "Unsolicited accepted", agent: false, status: "open",
      desc: "New Zealand's oldest university press, publishing non-fiction, poetry, and fiction. Accepts unsolicited manuscripts.",
      url: "https://oup.nz/submissions/" },
    { name: "Penguin Random House Australia", org: "Penguin Random House", region: "Australia", location: "Sydney, NSW",
      genres: ["Fiction","Non-fiction","Children's","Young Adult"], type: "Major Publisher",
      submission: "Agent preferred (also Penguin Literary Prize)", agent: true, status: "check",
      desc: "Australia's largest publisher. Agent preferred for unsolicited submissions, but runs the annual Penguin Literary Prize for direct submissions.",
      url: "https://www.penguinrandomhouse.com.au/" },
    { name: "HarperCollins Australia", org: "HarperCollins", region: "Australia", location: "Sydney, NSW",
      genres: ["Fiction","Non-fiction","Children's","Young Adult"], type: "Major Publisher",
      submission: "Agent required (Banjo Prize open)", agent: true, status: "check",
      desc: "Major international publisher. Agent required for general submissions, but runs the Banjo Prize for direct manuscript submissions.",
      url: "https://www.harpercollins.com.au/" },
    { name: "Tin House Books", org: "Tin House", region: "International", location: "Portland, OR, USA",
      genres: ["Literary Fiction","Non-fiction","Poetry"], type: "Independent Publisher",
      submission: "Agent preferred / open periods", agent: false, status: "check",
      desc: "Prestigious US independent publisher known for literary fiction, non-fiction, and poetry. Has open submission periods.",
      url: "https://tinhouse.com/submissions/" },
    { name: "Graywolf Press", org: "Graywolf Press", region: "International", location: "Minneapolis, MN, USA",
      genres: ["Literary Fiction","Non-fiction","Poetry"], type: "Independent Publisher",
      submission: "Agent preferred", agent: true, status: "check",
      desc: "One of America's most respected independent publishers of literary fiction, non-fiction, and poetry. Agent preferred.",
      url: "https://www.graywolfpress.org/" },
    { name: "Penguin Random House (Global)", org: "Penguin Random House", region: "International", location: "New York, USA / London, UK",
      genres: ["Fiction","Non-fiction","Children's","Young Adult"], type: "Major International Publisher",
      submission: "Agent required (international)", agent: true, status: "check",
      desc: "The world's largest publisher. Agent required for international submissions. Publishes across all genres.",
      url: "https://www.penguinrandomhouse.com/" },
  ],

};
